name: PopPang BE PR CI

on:
  pull_request:
    branches:
      - main

  workflow_dispatch:

permissions:
  contents: read

jobs:
  pr-ci:
    name: PR CI
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
          cache: gradle

      - name: Grant execute permission
        run: chmod +x gradlew

      - name: Test and format check
        run: ./gradlew clean test spotlessCheck --no-daemon
